# Compile viewts under linux

name: linux compile

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
    - name: Build tstools
      uses: lukka/run-cmake@v0
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: 'CMakeLists.txt'
        useVcpkgToolchainFile: true
        buildDirectory: '.'
        cmakeAppendedArgs: 'build --target all'    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.2.1
      timeout-minutes: 10
      with:
        target: desktop
        host: linux
        install-deps: true
        modules: qtcharts
    - name: Build Qt
      run: |
        cd qt_tstools/
        qmake viewTS.pro -spec linux-g++
        make
