# Compile viewts under linux

name: linux compile

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
    - name: Build tstools
      run: |
        cmake .
        cmake --build . --target all
    - name: Google test
      run: |
        cd bin/linux && tstool_tests
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.2.1
      timeout-minutes: 10
      with:
        target: desktop
        host: linux
        install-deps: true
        modules: qtcharts
    - name: Build Qt
      run: |
        cd qt_tstools/
        qmake viewTS.pro -spec linux-g++
        make
